In [1]:
import numpy as np

In [22]:
def func_y(x):
    y = x**2 - 4*x + 2
    return y
def gradient_descent(previous_x, learning_rate, epoch):
    
    # To fill with values
    x_gd = []
    y_gd = []
    
    x_gd.append(previous_x)
    y_gd.append(func_y(previous_x))
    # begin the loops to update x and y with out cost function
    for i in range(epoch):
        current_x = previous_x - learning_rate * (2*previous_x - 4)
        x_gd.append(current_x)
        y_gd.append(func_y(current_x))
        # update previous_x
        previous_x = current_x
    return x_gd, y_gd
# Initialize x0 and learning rate
x0 = 4 # Our first 'guess' at what theta could be
learning_rate = 0.15 # Alpha
epoch = 100 # Number of tries

In [23]:
a,b = gradient_descent(x0, learning_rate, epoch)

In [24]:
print(a)

[4, 3.4, 2.98, 2.686, 2.4802, 2.33614, 2.235298, 2.1647086, 2.11529602, 2.0807072140000002, 2.0564950498, 2.03954653486, 2.027682574402, 2.0193778020814, 2.01356446145698, 2.009495123019886, 2.0066465861139204, 2.004652610279744, 2.003256827195821, 2.0022797790370745, 2.0015958453259524, 2.0011170917281667, 2.0007819642097164, 2.0005473749468017, 2.0003831624627613, 2.000268213723933, 2.000187749606753, 2.000131424724727, 2.000091997307309, 2.0000643981151165, 2.0000450786805817, 2.000031555076407, 2.000022088553485, 2.0000154619874393, 2.0000108233912073, 2.000007576373845, 2.0000053034616916, 2.000003712423184, 2.000002598696229, 2.0000018190873603, 2.000001273361152, 2.0000008913528067, 2.0000006239469648, 2.000000436762875, 2.0000003057340128, 2.000000214013809, 2.000000149809666, 2.0000001048667664, 2.0000000734067367, 2.0000000513847156, 2.000000035969301, 2.000000025178511, 2.0000000176249575, 2.00000001233747, 2.000000008636229, 2.00000000604536, 2.0000000042317523, 2.000000002

In [25]:
print(b)

[2, -0.040000000000000924, -1.0396, -1.5294040000000004, -1.7694079599999997, -1.8870099003999998, -1.9446348511959997, -1.9728710770860403, -1.9867068277721591, -1.9934863456083578, -1.9968083093480953, -1.9984360715805671, -1.9992336750744775, -1.999624500786494, -1.999816005385382, -1.9999098426388375, -1.99995582289303, -1.9999783532175845, -1.9999893930766168, -1.9999948026075423, -1.9999974532776958, -1.9999987521060705, -1.9999993885319745, -1.999999700380668, -1.9999998531865275, -1.9999999280613983, -1.999999964750085, -1.9999999827275419, -1.9999999915364954, -1.9999999958528827, -1.9999999979679126, -1.9999999990042774, -1.999999999512096, -1.9999999997609272, -1.9999999998828546, -1.9999999999425988, -1.9999999999718732, -1.9999999999862181, -1.9999999999932472, -1.9999999999966906, -1.9999999999983782, -1.999999999999205, -1.999999999999611, -1.999999999999809, -1.9999999999999067, -1.9999999999999538, -1.9999999999999778, -1.9999999999999893, -1.9999999999999947, -1.99999

In [8]:
print(len(a))
print(len(b))

11
11


# the idea taken from https://towardsdatascience.com/implementation-of-multi-variate-linear-regression-in-python-using-gradient-descent-optimization-b02f386425b9

In [1]:
import numpy as np

In [2]:
A = [[1,2,3,4],[8,5,2,5],[6,3,9,7]]
A = np.array(A)

In [3]:
A

array([[1, 2, 3, 4],
       [8, 5, 2, 5],
       [6, 3, 9, 7]])

In [9]:
X_train = A[:,:-1]
y_train = A[:,-1]
print(X_train.shape)
print(y_train.shape)

(3, 3)
(3,)


In [41]:
learning_rate = 0.15
num_iters = 3

In [78]:
def linear_regression(X, y, alpha, num_iters):
    n = X.shape[1] # n is number of feature
    print('number of feature: ',n)
    one_column = np.ones((X.shape[0],1))
    print('one column :', one_column)
    print('X is: ',X)
    X = np.concatenate((one_column, X), axis = 1)
    print('now X: ',X)
    # initializing the parameter vector...
    theta = np.zeros(n+1)
    print('theta: ', theta)
    # hypothesis calculation....
    h = hypothesis(theta, X, n)
    # returning the optimized parameters by Gradient Descent...
    theta, cost = BGD(theta,alpha,num_iters,h,X,y,n)
    return theta, cost

def BGD(theta, alpha, num_iters, h, X, y, n):
    print('coming input in BGD: theta',theta,'\n h: ',h,'\n y: ',y,'\n X shape: ', X.shape)
    print('after getting now h here BGD func will work')
    cost = np.ones(num_iters)
    print('cost: ', cost)
    for i in range(0,num_iters):
        print('---------here h and y : ', h,'\t',y)
        print('sum h-y: ', sum(h-y))
        theta[0] = theta[0] - (alpha/X.shape[0]) * sum(h - y)
        print('theta o in BGD: ', theta[0])
        for j in range(1,n+1):
            print('j: ',j, ' ,X transpose: ', X.transpose()[j])
            print('alpha/X.shape[0]',(alpha/X.shape[0]))
            print('sum((h-y) * X.transpose()[j]', sum((h-y) * X.transpose()[j]))
            theta[j] = theta[j] - (alpha/X.shape[0]) * sum((h-y) * X.transpose()[j])
            print('theta j in BGD: ', theta[j])
        h = hypothesis(theta, X, n)
        cost[i] = (1/X.shape[0]) * 0.5 * sum(np.square(h - y))
        print('i: ',i,' ,COST -------', cost[i])
    theta = theta.reshape(1,n+1)
    return theta, cost

def hypothesis(theta, X, n):
    print('coming theta: ', theta)
    print('\n now hypothesis function')
    h = np.ones((X.shape[0],1))
    print('h: ',h)
    theta = theta.reshape(1,n+1)
    print('reshaped theta', theta)
    for i in range(0,X.shape[0]):
        h[i] = float(np.matmul(theta, X[i]))
    h = h.reshape(X.shape[0])
    print('now h: ',h)
    return h

In [79]:
theta, cost = linear_regression(X_train, y_train,learning_rate, num_iters)

number of feature:  3
one column : [[1.]
 [1.]
 [1.]]
X is:  [[1 2 3]
 [8 5 2]
 [6 3 9]]
now X:  [[1. 1. 2. 3.]
 [1. 8. 5. 2.]
 [1. 6. 3. 9.]]
theta:  [0. 0. 0. 0.]
coming theta:  [0. 0. 0. 0.]

 now hypothesis function
h:  [[1.]
 [1.]
 [1.]]
reshaped theta [[0. 0. 0. 0.]]
now h:  [0. 0. 0.]
coming input in BGD: theta [0. 0. 0. 0.] 
 h:  [0. 0. 0.] 
 y:  [4 5 7] 
 X shape:  (3, 4)
after getting now h here BGD func will work
cost:  [1. 1. 1.]
---------here h and y :  [0. 0. 0.] 	 [4 5 7]
sum h-y:  -16.0
theta o in BGD:  0.7999999999999999
j:  1  ,X transpose:  [1. 8. 6.]
alpha/X.shape[0] 0.049999999999999996
sum((h-y) * X.transpose()[j] -86.0
theta j in BGD:  4.3
j:  2  ,X transpose:  [2. 5. 3.]
alpha/X.shape[0] 0.049999999999999996
sum((h-y) * X.transpose()[j] -54.0
theta j in BGD:  2.6999999999999997
j:  3  ,X transpose:  [3. 2. 9.]
alpha/X.shape[0] 0.049999999999999996
sum((h-y) * X.transpose()[j] -85.0
theta j in BGD:  4.25
coming theta:  [0.8  4.3  2.7  4.25]

 now hypothesis funct

In [22]:
print(theta)

[[-3.44113812e+08 -2.07007978e+09 -1.24246965e+09 -1.87533872e+09]]


In [23]:
print(cost)

[1.24080083e+03 1.06866114e+05 9.20691098e+06 7.93211625e+08
 6.83383058e+10 5.88761421e+12 5.07241155e+14 4.37008234e+16
 3.76499806e+18 3.24369413e+20]


In [24]:
from sklearn import linear_model

In [25]:
clf = linear_model.SGDRegressor(max_iter=num_iters, alpha= learning_rate)

In [26]:
clf.fit(X_train, y_train)

SGDRegressor(alpha=0.15, average=False, epsilon=0.1, eta0=0.01,
       fit_intercept=True, l1_ratio=0.15, learning_rate='invscaling',
       loss='squared_loss', max_iter=10, n_iter=None, penalty='l2',
       power_t=0.25, random_state=None, shuffle=True, tol=None, verbose=0,
       warm_start=False)

In [27]:
print('Slope:' ,clf.coef_)
print('Intercept:', clf.intercept_)

Slope: [0.27884363 0.32251253 0.48547914]
Intercept: [0.14142455]


In [28]:
clf = linear_model.GDRegressor(max_iter=num_iters, alpha= learning_rate)

AttributeError: module 'sklearn.linear_model' has no attribute 'GDRegressor'